# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Matti Rita-Kasari
#
# AI Provenance & Liability Notice:
# This repository contains code generated, assisted, or refactored by Artificial
# Intelligence models. Provided strictly "AS IS" under Apache 2.0 with no warranty
# of clean IP provenance or non-infringement; downstream users assume all legal
# and financial risk and should perform their own compliance audits.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from __future__ import annotations

from .archetypes import ARCHETYPES, ARCHETYPE_SPEED_BY_NAME, DUNGEON_THEMES
from .definitions import (
    BossDefinition,
    DifficultyProfile,
    EncounterTemplate,
    EnemyAbility,
    EnemyDefinition,
    EquipmentDefinition,
    Tactic,
    InteractionHint,
    RarityProfile,
    StoryBackstory,
    StoryDilemmaTemplate,
    StoryFaction,
    StoryGuestTemplate,
    StoryLocationMotif,
    StoryRelic,
)
from .difficulty import (
    DEFAULT_DIFFICULTY_NAME,
    DIFFICULTY_PROFILES,
    HELL_DIFFICULTY_NAME,
)
from .enemies import (
    ABILITY_INDEX,
    BOSS_DEFINITIONS,
    canonical_boss_name,
    DEFAULT_MELEE_TACTIC,
    DEFAULT_RANGED_TACTIC,
    ENCOUNTER_TEMPLATES,
    ENEMY_ABILITIES,
    ENEMY_DEFINITIONS,
    FINAL_ROOM_ENEMY_DEFINITIONS,
    HUMANOID_ENEMY_NAMES,
    TACTICS,
)
from .equipment import (
    AFFIX_DEFINITIONS,
    ARMOR_DEFINITIONS,
    MAX_ROLLED_ARMOR_DEFENSE,
    MAX_ROLLED_WEAPON_POWER,
    RARITY_AFFIX_COUNTS,
    RARITY_AFFIX_ROLL_RANGES,
    RARITY_PROFILES,
    UNIQUE_ARMOR_MIN_DEPTH,
    UNIQUE_ITEM_DEFINITIONS,
    WEAPON_DEFINITIONS,
    AffixDefinition,
    UniqueItemDefinition,
)
from .interactables import (
    SECRET_HINTS,
    SECRET_TYPES,
    SHRINE_HINTS,
    SHRINE_TYPES,
    TRAP_DEFINITIONS,
    TRAP_HINTS,
)
from .progression import (
    COMBO_BONUS_PER_STEP_MAX_HP,
    COMBO_BONUS_PER_STEP_MELEE,
    COMBO_BONUS_PER_STEP_SPELL,
    COMPLETED_PATH_BONUS_MAX_HP,
    COMPLETED_PATH_BONUS_MELEE,
    COMPLETED_PATH_BONUS_SPELL,
    ELITE_MODIFIERS,
    LEGACY_DISCIPLINE_KEYS,
    MAX_COMMITTED_PATHS,
    RUN_MODIFIERS,
    DISCIPLINES,
    DISCIPLINE_SPEED_BONUS_BY_KEY,
    DISCIPLINE_UPGRADES,
    path_progress,
    combo_bonus,
    combo_bonus_preview,
    combo_bonus_steps,
    committed_paths,
    completed_path_bonus,
    completed_paths,
    cross_path_tag_bonus,
    is_path_locked,
    migrate_discipline_keys,
    discipline_path_nodes,
    discipline_paths_for_archetype,
    discipline_by_key,
    disciplines_for_archetype,
    max_discipline_degree,
)
from .story_corpus import (
    BOSS_LAST_WORDS,
    BOSS_MIRROR_OMEN_LINES,
    BOSS_OMEN_LINES,
    RUE_DEATH_LINES,
    SHOP_PATTER_LINES,
    STORY_ARCS,
    STORY_BACKSTORIES,
    STORY_CORPUS,
    STORY_CRISIS_ECHOES,
    STORY_DILEMMAS,
    STORY_ENDING_FORSAKEN_CODAS,
    STORY_ENDING_ROAD_CODAS,
    STORY_ENDINGS,
    STORY_FACTIONS,
    STORY_GATE_CHOICES,
    STORY_GUEST_TEMPLATES,
    STORY_LOCATION_MOTIFS,
    STORY_RELICS,
    STORY_ROAD_LINES,
    STORY_TETHERS,
    TYRANT_OFFERS,
)

__all__ = [
    "ABILITY_INDEX",
    "AFFIX_DEFINITIONS",
    "ARCHETYPES",
    "ARCHETYPE_SPEED_BY_NAME",
    "ARMOR_DEFINITIONS",
    "AffixDefinition",
    "BOSS_DEFINITIONS",
    "canonical_boss_name",
    "BossDefinition",
    "DEFAULT_MELEE_TACTIC",
    "DEFAULT_RANGED_TACTIC",
    "DEFAULT_DIFFICULTY_NAME",
    "DIFFICULTY_PROFILES",
    "DUNGEON_THEMES",
    "DifficultyProfile",
    "COMBO_BONUS_PER_STEP_MAX_HP",
    "COMBO_BONUS_PER_STEP_MELEE",
    "COMBO_BONUS_PER_STEP_SPELL",
    "COMPLETED_PATH_BONUS_MAX_HP",
    "COMPLETED_PATH_BONUS_MELEE",
    "COMPLETED_PATH_BONUS_SPELL",
    "ELITE_MODIFIERS",
    "ENCOUNTER_TEMPLATES",
    "ENEMY_ABILITIES",
    "ENEMY_DEFINITIONS",
    "EncounterTemplate",
    "EnemyAbility",
    "EnemyDefinition",
    "EquipmentDefinition",
    "TACTICS",
    "Tactic",
    "FINAL_ROOM_ENEMY_DEFINITIONS",
    "HELL_DIFFICULTY_NAME",
    "HUMANOID_ENEMY_NAMES",
    "InteractionHint",
    "LEGACY_DISCIPLINE_KEYS",
    "MAX_COMMITTED_PATHS",
    "MAX_ROLLED_ARMOR_DEFENSE",
    "MAX_ROLLED_WEAPON_POWER",
    "RARITY_AFFIX_COUNTS",
    "RARITY_AFFIX_ROLL_RANGES",
    "RARITY_PROFILES",
    "RUN_MODIFIERS",
    "RarityProfile",
    "SECRET_HINTS",
    "SECRET_TYPES",
    "SHRINE_HINTS",
    "SHRINE_TYPES",
    "DISCIPLINE_SPEED_BONUS_BY_KEY",
    "DISCIPLINE_UPGRADES",
    "DISCIPLINES",
    "path_progress",
    "committed_paths",
    "is_path_locked",
    "BOSS_LAST_WORDS",
    "BOSS_MIRROR_OMEN_LINES",
    "BOSS_OMEN_LINES",
    "RUE_DEATH_LINES",
    "SHOP_PATTER_LINES",
    "STORY_ARCS",
    "STORY_BACKSTORIES",
    "STORY_CORPUS",
    "STORY_CRISIS_ECHOES",
    "STORY_DILEMMAS",
    "STORY_ENDING_FORSAKEN_CODAS",
    "STORY_ENDING_ROAD_CODAS",
    "STORY_ENDINGS",
    "STORY_FACTIONS",
    "STORY_GATE_CHOICES",
    "STORY_GUEST_TEMPLATES",
    "STORY_LOCATION_MOTIFS",
    "STORY_RELICS",
    "STORY_ROAD_LINES",
    "STORY_TETHERS",
    "TYRANT_OFFERS",
    "StoryArc",
    "StoryBackstory",
    "StoryCrisisChoice",
    "StoryDilemmaTemplate",
    "StoryEnding",
    "StoryFaction",
    "StoryGuestTemplate",
    "StoryLocationMotif",
    "StoryRelic",
    "StoryTether",
    "StoryTetherBeat",
    "combo_bonus",
    "combo_bonus_preview",
    "combo_bonus_steps",
    "completed_path_bonus",
    "completed_paths",
    "cross_path_tag_bonus",
    "migrate_discipline_keys",
    "discipline_path_nodes",
    "discipline_paths_for_archetype",
    "discipline_by_key",
    "disciplines_for_archetype",
    "max_discipline_degree",
    "TRAP_DEFINITIONS",
    "TRAP_HINTS",
    "UNIQUE_ARMOR_MIN_DEPTH",
    "UNIQUE_ITEM_DEFINITIONS",
    "UniqueItemDefinition",
    "WEAPON_DEFINITIONS",
]
