package archrogue

// Character progression data and rules. This file is deliberately raylib-free:
// the character sheet and future save layer consume the same stable IDs and
// pure acquisition helpers as headless simulation tests.
// Definitions are a field-for-field port of
// src/arch_rogue/content/progression.py::DISCIPLINES (100 nodes).

MAX_COMMITTED_DISCIPLINE_PATHS :: 2
DISCIPLINE_COUNT :: 100
DISCIPLINE_DEGREES :: 5
DISCIPLINE_PATHS_PER_ARCHETYPE :: 4

Discipline_Id :: enum u8 {
	Warden_Bulwark,
	Warden_Riposte,
	Warden_Aegis,
	Warden_Counter,
	Warden_Bulwark_Ward,
	Warden_Riposte_Edge,
	Warden_Iron_Vow,
	Warden_Reckoning,
	Warden_Unbreakable,
	Warden_Final_Reckoning,
	Warden_Smite,
	Warden_Ward,
	Warden_Judgment,
	Warden_Bulwark_Wave,
	Warden_Consecrate,
	Warden_Stone_Aegis,
	Warden_Divine_Wrath,
	Warden_Unyielding,
	Warden_Avatar_Of_Light,
	Warden_Eternal_Wall,
	Rogue_Precision,
	Rogue_Smoke,
	Rogue_Venom,
	Rogue_Shadowstep,
	Rogue_Executioner,
	Rogue_Night_Veil,
	Rogue_Crimson_Edge,
	Rogue_Phantom,
	Rogue_Deathmark,
	Rogue_Umbral,
	Rogue_Trap_Craft,
	Rogue_Marksman,
	Rogue_Venom_Trap,
	Rogue_Sharpshot,
	Rogue_Bear_Trap,
	Rogue_Deadeye,
	Rogue_Trap_Master,
	Rogue_Eagle_Eye,
	Rogue_Ambush_Engineer,
	Rogue_Assassin,
	Arcanist_Splinter,
	Arcanist_Focus,
	Arcanist_Permafrost,
	Arcanist_Overload,
	Arcanist_Glacial,
	Arcanist_Pierce,
	Arcanist_Blizzard,
	Arcanist_Storm,
	Arcanist_Absolute_Zero,
	Arcanist_Arc_Tyrant,
	Arcanist_Charge,
	Arcanist_Ward,
	Arcanist_Chain_Lightning,
	Arcanist_Ward_Mend,
	Arcanist_Tempest,
	Arcanist_Ward_Overload,
	Arcanist_Storm_Caller,
	Arcanist_Aegis,
	Arcanist_World_Storm,
	Arcanist_Eternal_Aegis,
	Acolyte_Sanguine,
	Acolyte_Veil,
	Acolyte_Gravebind,
	Acolyte_Ashen,
	Acolyte_Blood_Pact,
	Acolyte_Spirit_Host,
	Acolyte_Crimson_Maw,
	Acolyte_Grave_Chorus,
	Acolyte_Sanguine_Ascendant,
	Acolyte_Undying_Veil,
	Acolyte_Spirit_Call,
	Acolyte_Curse,
	Acolyte_Wraith_Host,
	Acolyte_Decay,
	Acolyte_Bone_Legion,
	Acolyte_Fragility,
	Acolyte_Wraith_Lord,
	Acolyte_Doom,
	Acolyte_Legion_Eternal,
	Acolyte_Eternal_Doom,
	Ranger_Snare,
	Ranger_Volley,
	Ranger_Beastmark,
	Ranger_Rapid,
	Ranger_Thornfield,
	Ranger_Piercing_Volley,
	Ranger_Hunter_Drive,
	Ranger_Storm_Volley,
	Ranger_Wild_Domination,
	Ranger_Sky_Quiver,
	Ranger_Beast_Bond,
	Ranger_Survival,
	Ranger_Pack_Tactics,
	Ranger_Camouflage,
	Ranger_Alpha,
	Ranger_Pathfinder,
	Ranger_Spirit_Companion,
	Ranger_Ambush,
	Ranger_Primal_Lord,
	Ranger_Ghost_Step,
}

Discipline_Path :: enum u8 {
	Warden_Bulwark,
	Warden_Riposte,
	Warden_Vow,
	Warden_Time,
	Rogue_Precision,
	Rogue_Shadow,
	Rogue_Traps,
	Rogue_Marksman,
	Arcanist_Bolt,
	Arcanist_Nova,
	Arcanist_Storm,
	Arcanist_Ward,
	Acolyte_Blood,
	Acolyte_Veil,
	Acolyte_Spirit,
	Acolyte_Curse,
	Ranger_Control,
	Ranger_Volley,
	Ranger_Beast,
	Ranger_Survival,
}

Discipline_Tag :: enum u8 {
	None,
	Aim,
	Arcane,
	Beast,
	Blood,
	Control,
	Counter,
	Critical,
	Curse,
	Frost,
	Guard,
	Holy,
	Shield,
	Spirit,
	Stealth,
	Storm,
	Survival,
	Time,
	Trap,
	Veil,
	Volley,
}

// Untracked is intentionally the zero value. Table validation fails if a new
// node is added without declaring how much of its bespoke behavior is ported.
// Fully_Wired marks nodes whose player-facing text is completely represented
// at runtime (MX.3); Stats_Only remains for nodes that only promise stats.
Discipline_Effect_Coverage :: enum u8 {
	Untracked,
	Stats_Only,
	Partially_Wired,
	Deferred,
	Fully_Wired,
}

Discipline_Def :: struct {
	key:                      string,
	name:                     string,
	description:              string,
	archetype:                Archetype_Id,
	path:                     Discipline_Path,
	degree:                   u8,
	has_prerequisite:         bool,
	prerequisite:             Discipline_Id,
	melee_bonus:              int,
	spell_bonus:              int,
	armor_bonus:              int,
	max_hp_bonus:             int,
	max_mana_bonus:           int,
	max_stamina_bonus:        int,
	speed_bonus:              f32,
	tag:                      Discipline_Tag,
	cross_path_tag:           Discipline_Tag,
	cross_path_bonus_melee:   int,
	cross_path_bonus_spell:   int,
	effect_coverage:          Discipline_Effect_Coverage,
}

Discipline_Path_Def :: struct {
	name:      string,
	archetype: Archetype_Id,
}

@(rodata)
DISCIPLINE_PATH_DEFS := [Discipline_Path]Discipline_Path_Def{
	.Warden_Bulwark = {"Bulwark", .Warden},
	.Warden_Riposte = {"Riposte", .Warden},
	.Warden_Vow = {"Vow", .Warden},
	.Warden_Time = {"Time", .Warden},
	.Rogue_Precision = {"Precision", .Rogue},
	.Rogue_Shadow = {"Shadow", .Rogue},
	.Rogue_Traps = {"Traps", .Rogue},
	.Rogue_Marksman = {"Marksman", .Rogue},
	.Arcanist_Bolt = {"Bolt", .Arcanist},
	.Arcanist_Nova = {"Nova", .Arcanist},
	.Arcanist_Storm = {"Storm", .Arcanist},
	.Arcanist_Ward = {"Ward", .Arcanist},
	.Acolyte_Blood = {"Blood", .Acolyte},
	.Acolyte_Veil = {"Veil", .Acolyte},
	.Acolyte_Spirit = {"Spirit", .Acolyte},
	.Acolyte_Curse = {"Curse", .Acolyte},
	.Ranger_Control = {"Control", .Ranger},
	.Ranger_Volley = {"Volley", .Ranger},
	.Ranger_Beast = {"Beast", .Ranger},
	.Ranger_Survival = {"Survival", .Ranger},
}

@(rodata)
DISCIPLINE_PATH_LAYOUT := [Archetype_Id][DISCIPLINE_PATHS_PER_ARCHETYPE]Discipline_Path{
	.Warden = {.Warden_Bulwark, .Warden_Riposte, .Warden_Vow, .Warden_Time},
	.Rogue = {.Rogue_Precision, .Rogue_Shadow, .Rogue_Traps, .Rogue_Marksman},
	.Arcanist = {.Arcanist_Bolt, .Arcanist_Nova, .Arcanist_Storm, .Arcanist_Ward},
	.Acolyte = {.Acolyte_Blood, .Acolyte_Veil, .Acolyte_Spirit, .Acolyte_Curse},
	.Ranger = {.Ranger_Control, .Ranger_Volley, .Ranger_Beast, .Ranger_Survival},
}

@(rodata)
DISCIPLINES := [Discipline_Id]Discipline_Def{
	.Warden_Bulwark = {
		key = "warden_bulwark",
		name = "Bulwark Training",
		description = "Shield Bash becomes a slower, wider cleave.",
		archetype = .Warden,
		path = .Warden_Bulwark,
		degree = 1,
		has_prerequisite = false,
		prerequisite = .Warden_Bulwark,
		melee_bonus = 1,
		spell_bonus = 0,
		armor_bonus = 2,
		max_hp_bonus = 10,
		max_mana_bonus = 0,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Guard,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Warden_Riposte = {
		key = "warden_riposte",
		name = "Riposte Guard",
		description = "Melee hits hurt less and trigger a holy counterattack.",
		archetype = .Warden,
		path = .Warden_Riposte,
		degree = 1,
		has_prerequisite = false,
		prerequisite = .Warden_Bulwark,
		melee_bonus = 2,
		spell_bonus = 0,
		armor_bonus = 1,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Counter,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Warden_Aegis = {
		key = "warden_aegis",
		name = "Aegis Discipline",
		description = "Guard Step briefly hardens the Warden; Shield Bash becomes a farther-reaching holy stun, and counters also stun.",
		archetype = .Warden,
		path = .Warden_Bulwark,
		degree = 2,
		has_prerequisite = true,
		prerequisite = .Warden_Bulwark,
		melee_bonus = 0,
		spell_bonus = 0,
		armor_bonus = 1,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 8,
		speed_bonus = 0.0,
		tag = .Guard,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Warden_Counter = {
		key = "warden_counter",
		name = "Counter Stance",
		description = "Improves melee power and stamina reserves.",
		archetype = .Warden,
		path = .Warden_Riposte,
		degree = 2,
		has_prerequisite = true,
		prerequisite = .Warden_Riposte,
		melee_bonus = 2,
		spell_bonus = 0,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 6,
		speed_bonus = 0.0,
		tag = .Counter,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Warden_Bulwark_Ward = {
		key = "warden_bulwark_ward",
		name = "Warden's Ward",
		description = "Shield Bash reaches farther still and cleaves through more nearby foes.",
		archetype = .Warden,
		path = .Warden_Bulwark,
		degree = 3,
		has_prerequisite = true,
		prerequisite = .Warden_Aegis,
		melee_bonus = 0,
		spell_bonus = 0,
		armor_bonus = 2,
		max_hp_bonus = 12,
		max_mana_bonus = 0,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Guard,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Warden_Riposte_Edge = {
		key = "warden_riposte_edge",
		name = "Riposte Edge",
		description = "Further improves melee power and armor.",
		archetype = .Warden,
		path = .Warden_Riposte,
		degree = 3,
		has_prerequisite = true,
		prerequisite = .Warden_Counter,
		melee_bonus = 3,
		spell_bonus = 0,
		armor_bonus = 1,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Counter,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Warden_Iron_Vow = {
		key = "warden_iron_vow",
		name = "Iron Vow",
		description = "Greatly strengthens armor, vitality, and stamina reserves.",
		archetype = .Warden,
		path = .Warden_Bulwark,
		degree = 4,
		has_prerequisite = true,
		prerequisite = .Warden_Bulwark_Ward,
		melee_bonus = 0,
		spell_bonus = 0,
		armor_bonus = 3,
		max_hp_bonus = 14,
		max_mana_bonus = 0,
		max_stamina_bonus = 12,
		speed_bonus = 0.0,
		tag = .Guard,
		cross_path_tag = .Counter,
		cross_path_bonus_melee = 1,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Warden_Reckoning = {
		key = "warden_reckoning",
		name = "Reckoning",
		description = "Improves melee power, Guard Bolt damage, and mana reserves.",
		archetype = .Warden,
		path = .Warden_Riposte,
		degree = 4,
		has_prerequisite = true,
		prerequisite = .Warden_Riposte_Edge,
		melee_bonus = 4,
		spell_bonus = 2,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 10,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Counter,
		cross_path_tag = .Guard,
		cross_path_bonus_melee = 1,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Warden_Unbreakable = {
		key = "warden_unbreakable",
		name = "Unbreakable Bulwark",
		description = "Grants the path's greatest armor and vitality boost, with deeper stamina reserves.",
		archetype = .Warden,
		path = .Warden_Bulwark,
		degree = 5,
		has_prerequisite = true,
		prerequisite = .Warden_Iron_Vow,
		melee_bonus = 0,
		spell_bonus = 0,
		armor_bonus = 4,
		max_hp_bonus = 24,
		max_mana_bonus = 0,
		max_stamina_bonus = 10,
		speed_bonus = 0.0,
		tag = .None,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Warden_Final_Reckoning = {
		key = "warden_final_reckoning",
		name = "Final Reckoning",
		description = "Greatly improves melee power, Guard Bolt damage, and stamina reserves.",
		archetype = .Warden,
		path = .Warden_Riposte,
		degree = 5,
		has_prerequisite = true,
		prerequisite = .Warden_Reckoning,
		melee_bonus = 5,
		spell_bonus = 3,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 10,
		speed_bonus = 0.0,
		tag = .None,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Warden_Smite = {
		key = "warden_smite",
		name = "Smite Oath",
		description = "Strengthens Guard Bolt and expands mana reserves.",
		archetype = .Warden,
		path = .Warden_Vow,
		degree = 1,
		has_prerequisite = false,
		prerequisite = .Warden_Bulwark,
		melee_bonus = 0,
		spell_bonus = 2,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 8,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Holy,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Warden_Ward = {
		key = "warden_ward",
		name = "Temporal Sigil",
		description = "Time Skip costs less mana, cools down faster, and lasts a beat longer.",
		archetype = .Warden,
		path = .Warden_Time,
		degree = 1,
		has_prerequisite = false,
		prerequisite = .Warden_Bulwark,
		melee_bonus = 0,
		spell_bonus = 0,
		armor_bonus = 2,
		max_hp_bonus = 8,
		max_mana_bonus = 0,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Time,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Warden_Judgment = {
		key = "warden_judgment",
		name = "Judgment",
		description = "Further strengthens Guard Bolt and mana reserves.",
		archetype = .Warden,
		path = .Warden_Vow,
		degree = 2,
		has_prerequisite = true,
		prerequisite = .Warden_Smite,
		melee_bonus = 0,
		spell_bonus = 3,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 8,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Holy,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Warden_Bulwark_Wave = {
		key = "warden_bulwark_wave",
		name = "Time Skip",
		description = "Time Skip lasts longer and its cast pulse briefly stuns and delays nearby foes.",
		archetype = .Warden,
		path = .Warden_Time,
		degree = 2,
		has_prerequisite = true,
		prerequisite = .Warden_Ward,
		melee_bonus = 0,
		spell_bonus = 0,
		armor_bonus = 2,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 8,
		speed_bonus = 0.0,
		tag = .Time,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Warden_Consecrate = {
		key = "warden_consecrate",
		name = "Consecration",
		description = "Deepens Guard Bolt damage and mana reserves.",
		archetype = .Warden,
		path = .Warden_Vow,
		degree = 3,
		has_prerequisite = true,
		prerequisite = .Warden_Judgment,
		melee_bonus = 0,
		spell_bonus = 4,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 10,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Holy,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Warden_Stone_Aegis = {
		key = "warden_stone_aegis",
		name = "Stutter Step",
		description = "Time Skip slows enemies harder while it lasts.",
		archetype = .Warden,
		path = .Warden_Time,
		degree = 3,
		has_prerequisite = true,
		prerequisite = .Warden_Bulwark_Wave,
		melee_bonus = 0,
		spell_bonus = 0,
		armor_bonus = 3,
		max_hp_bonus = 12,
		max_mana_bonus = 0,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Time,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Warden_Divine_Wrath = {
		key = "warden_divine_wrath",
		name = "Divine Wrath",
		description = "Greatly strengthens Guard Bolt and mana reserves.",
		archetype = .Warden,
		path = .Warden_Vow,
		degree = 4,
		has_prerequisite = true,
		prerequisite = .Warden_Consecrate,
		melee_bonus = 0,
		spell_bonus = 5,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 12,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Holy,
		cross_path_tag = .Counter,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 1,
		effect_coverage = .Stats_Only,
	},
	.Warden_Unyielding = {
		key = "warden_unyielding",
		name = "Temporal Aegis",
		description = "While Time Skip is active the Warden takes reduced damage.",
		archetype = .Warden,
		path = .Warden_Time,
		degree = 4,
		has_prerequisite = true,
		prerequisite = .Warden_Stone_Aegis,
		melee_bonus = 0,
		spell_bonus = 0,
		armor_bonus = 4,
		max_hp_bonus = 16,
		max_mana_bonus = 0,
		max_stamina_bonus = 10,
		speed_bonus = 0.0,
		tag = .Time,
		cross_path_tag = .Guard,
		cross_path_bonus_melee = 1,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Warden_Avatar_Of_Light = {
		key = "warden_avatar_of_light",
		name = "Avatar of Light",
		description = "Grants the path's greatest Guard Bolt and mana boost while strengthening vitality.",
		archetype = .Warden,
		path = .Warden_Vow,
		degree = 5,
		has_prerequisite = true,
		prerequisite = .Warden_Divine_Wrath,
		melee_bonus = 0,
		spell_bonus = 6,
		armor_bonus = 0,
		max_hp_bonus = 12,
		max_mana_bonus = 16,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .None,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Warden_Eternal_Wall = {
		key = "warden_eternal_wall",
		name = "Eternal Moment",
		description = "Kills while Time Skip is active refund much of the slot's cooldown.",
		archetype = .Warden,
		path = .Warden_Time,
		degree = 5,
		has_prerequisite = true,
		prerequisite = .Warden_Unyielding,
		melee_bonus = 0,
		spell_bonus = 0,
		armor_bonus = 5,
		max_hp_bonus = 24,
		max_mana_bonus = 0,
		max_stamina_bonus = 12,
		speed_bonus = 0.0,
		tag = .None,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Rogue_Precision = {
		key = "rogue_precision",
		name = "Killing Precision",
		description = "Melee gains poisonous critical strikes and costs less stamina; Ambush Bell's damage and criticals improve.",
		archetype = .Rogue,
		path = .Rogue_Precision,
		degree = 1,
		has_prerequisite = false,
		prerequisite = .Warden_Bulwark,
		melee_bonus = 3,
		spell_bonus = 0,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 8,
		speed_bonus = 0.0,
		tag = .Critical,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Rogue_Smoke = {
		key = "rogue_smoke",
		name = "Smoke Step",
		description = "Shadow Dash travels farther for less stamina and grants Smoke; evasion improves, and Ambush Bell grants longer Smoke.",
		archetype = .Rogue,
		path = .Rogue_Shadow,
		degree = 1,
		has_prerequisite = false,
		prerequisite = .Warden_Bulwark,
		melee_bonus = 0,
		spell_bonus = 0,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 10,
		speed_bonus = 0.15,
		tag = .Stealth,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Rogue_Venom = {
		key = "rogue_venom",
		name = "Venomcraft",
		description = "Critical strikes become stronger, while Knife Fan and Ambush Bell poison their victims.",
		archetype = .Rogue,
		path = .Rogue_Precision,
		degree = 2,
		has_prerequisite = true,
		prerequisite = .Rogue_Precision,
		melee_bonus = 1,
		spell_bonus = 0,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 6,
		speed_bonus = 0.0,
		tag = .Critical,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Rogue_Shadowstep = {
		key = "rogue_shadowstep",
		name = "Shadowstep",
		description = "Expands stamina reserves and quickens your stride.",
		archetype = .Rogue,
		path = .Rogue_Shadow,
		degree = 2,
		has_prerequisite = true,
		prerequisite = .Rogue_Smoke,
		melee_bonus = 0,
		spell_bonus = 0,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 8,
		speed_bonus = 0.1,
		tag = .Stealth,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Rogue_Executioner = {
		key = "rogue_executioner",
		name = "Executioner",
		description = "Critical strikes become more frequent and deadly; Ambush Bell punishes poisoned prey.",
		archetype = .Rogue,
		path = .Rogue_Precision,
		degree = 3,
		has_prerequisite = true,
		prerequisite = .Rogue_Venom,
		melee_bonus = 4,
		spell_bonus = 0,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 6,
		speed_bonus = 0.0,
		tag = .Critical,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Rogue_Night_Veil = {
		key = "rogue_night_veil",
		name = "Night Veil",
		description = "Ambush Bell grants Smoke for longer, while stamina reserves improve.",
		archetype = .Rogue,
		path = .Rogue_Shadow,
		degree = 3,
		has_prerequisite = true,
		prerequisite = .Rogue_Shadowstep,
		melee_bonus = 0,
		spell_bonus = 0,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 12,
		speed_bonus = 0.08,
		tag = .Stealth,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Rogue_Crimson_Edge = {
		key = "rogue_crimson_edge",
		name = "Crimson Edge",
		description = "Critical strikes improve again, and Ambush Bell hits harder.",
		archetype = .Rogue,
		path = .Rogue_Precision,
		degree = 4,
		has_prerequisite = true,
		prerequisite = .Rogue_Executioner,
		melee_bonus = 5,
		spell_bonus = 0,
		armor_bonus = 0,
		max_hp_bonus = 10,
		max_mana_bonus = 0,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Critical,
		cross_path_tag = .Stealth,
		cross_path_bonus_melee = 1,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Rogue_Phantom = {
		key = "rogue_phantom",
		name = "Phantom",
		description = "Expands stamina reserves and quickens your stride.",
		archetype = .Rogue,
		path = .Rogue_Shadow,
		degree = 4,
		has_prerequisite = true,
		prerequisite = .Rogue_Night_Veil,
		melee_bonus = 0,
		spell_bonus = 0,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 10,
		speed_bonus = 0.12,
		tag = .Stealth,
		cross_path_tag = .Critical,
		cross_path_bonus_melee = 1,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Rogue_Deathmark = {
		key = "rogue_deathmark",
		name = "Deathmark",
		description = "Precision criticals reach their peak, and Ambush Bell gains further damage.",
		archetype = .Rogue,
		path = .Rogue_Precision,
		degree = 5,
		has_prerequisite = true,
		prerequisite = .Rogue_Crimson_Edge,
		melee_bonus = 6,
		spell_bonus = 0,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 10,
		speed_bonus = 0.0,
		tag = .None,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Rogue_Umbral = {
		key = "rogue_umbral",
		name = "Umbral Form",
		description = "Ambush Bell grants its longest Smoke window, while stamina reserves improve.",
		archetype = .Rogue,
		path = .Rogue_Shadow,
		degree = 5,
		has_prerequisite = true,
		prerequisite = .Rogue_Phantom,
		melee_bonus = 0,
		spell_bonus = 0,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 12,
		speed_bonus = 0.14,
		tag = .None,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Rogue_Trap_Craft = {
		key = "rogue_trap_craft",
		name = "Bellwright's Hand",
		description = "Ambush Bell arms faster, lasts longer, lures from farther away, and strikes harder.",
		archetype = .Rogue,
		path = .Rogue_Traps,
		degree = 1,
		has_prerequisite = false,
		prerequisite = .Warden_Bulwark,
		melee_bonus = 2,
		spell_bonus = 1,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 6,
		speed_bonus = 0.0,
		tag = .Trap,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Rogue_Marksman = {
		key = "rogue_marksman",
		name = "Marksman",
		description = "Improves bolt damage, melee power, and stamina reserves.",
		archetype = .Rogue,
		path = .Rogue_Marksman,
		degree = 1,
		has_prerequisite = false,
		prerequisite = .Warden_Bulwark,
		melee_bonus = 2,
		spell_bonus = 1,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 4,
		speed_bonus = 0.0,
		tag = .Aim,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Rogue_Venom_Trap = {
		key = "rogue_venom_trap",
		name = "Venom Chime",
		description = "Ambush Bell's burst poisons caught foes and deals stronger splash damage.",
		archetype = .Rogue,
		path = .Rogue_Traps,
		degree = 2,
		has_prerequisite = true,
		prerequisite = .Rogue_Trap_Craft,
		melee_bonus = 0,
		spell_bonus = 2,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 6,
		speed_bonus = 0.0,
		tag = .Trap,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Rogue_Sharpshot = {
		key = "rogue_sharpshot",
		name = "Sharpshot",
		description = "Further improves bolt damage, melee power, and stamina reserves.",
		archetype = .Rogue,
		path = .Rogue_Marksman,
		degree = 2,
		has_prerequisite = true,
		prerequisite = .Rogue_Marksman,
		melee_bonus = 3,
		spell_bonus = 1,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 4,
		speed_bonus = 0.0,
		tag = .Aim,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Rogue_Bear_Trap = {
		key = "rogue_bear_trap",
		name = "Iron Clapper",
		description = "Ambush Bell triggers more readily, snares its primary victim, and punishes lured prey.",
		archetype = .Rogue,
		path = .Rogue_Traps,
		degree = 3,
		has_prerequisite = true,
		prerequisite = .Rogue_Venom_Trap,
		melee_bonus = 3,
		spell_bonus = 2,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 6,
		speed_bonus = 0.0,
		tag = .Trap,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Rogue_Deadeye = {
		key = "rogue_deadeye",
		name = "Deadeye",
		description = "Greatly improves bolt damage, melee power, and stamina reserves.",
		archetype = .Rogue,
		path = .Rogue_Marksman,
		degree = 3,
		has_prerequisite = true,
		prerequisite = .Rogue_Sharpshot,
		melee_bonus = 4,
		spell_bonus = 2,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 4,
		speed_bonus = 0.0,
		tag = .Aim,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Rogue_Trap_Master = {
		key = "rogue_trap_master",
		name = "Resonant Lure",
		description = "Ambush Bell lures from farther away and unleashes a broader, stronger blast that prolongs poison and spreads snares.",
		archetype = .Rogue,
		path = .Rogue_Traps,
		degree = 4,
		has_prerequisite = true,
		prerequisite = .Rogue_Bear_Trap,
		melee_bonus = 4,
		spell_bonus = 3,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 8,
		speed_bonus = 0.0,
		tag = .Trap,
		cross_path_tag = .Critical,
		cross_path_bonus_melee = 1,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Rogue_Eagle_Eye = {
		key = "rogue_eagle_eye",
		name = "Eagle Eye",
		description = "Further improves bolt damage, melee power, and stamina reserves.",
		archetype = .Rogue,
		path = .Rogue_Marksman,
		degree = 4,
		has_prerequisite = true,
		prerequisite = .Rogue_Deadeye,
		melee_bonus = 5,
		spell_bonus = 2,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 4,
		speed_bonus = 0.0,
		tag = .Aim,
		cross_path_tag = .Stealth,
		cross_path_bonus_melee = 1,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Rogue_Ambush_Engineer = {
		key = "rogue_ambush_engineer",
		name = "Cursed Bellwright",
		description = "Ambush Bell arms faster, reaches farther, and hits harder; kills hasten recovery and restore mana.",
		archetype = .Rogue,
		path = .Rogue_Traps,
		degree = 5,
		has_prerequisite = true,
		prerequisite = .Rogue_Trap_Master,
		melee_bonus = 5,
		spell_bonus = 4,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 10,
		speed_bonus = 0.0,
		tag = .None,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Rogue_Assassin = {
		key = "rogue_assassin",
		name = "Assassin",
		description = "Grants the path's greatest bolt and melee power boost, with deeper stamina reserves.",
		archetype = .Rogue,
		path = .Rogue_Marksman,
		degree = 5,
		has_prerequisite = true,
		prerequisite = .Rogue_Eagle_Eye,
		melee_bonus = 6,
		spell_bonus = 3,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 6,
		speed_bonus = 0.0,
		tag = .None,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Arcanist_Splinter = {
		key = "arcanist_splinter",
		name = "Splintered Arcana",
		description = "Arc Bolt splinters into longer-lived shards.",
		archetype = .Arcanist,
		path = .Arcanist_Bolt,
		degree = 1,
		has_prerequisite = false,
		prerequisite = .Warden_Bulwark,
		melee_bonus = 0,
		spell_bonus = 3,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 10,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Arcane,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Arcanist_Focus = {
		key = "arcanist_focus",
		name = "Deep Focus",
		description = "Mana recovers faster while Frost Nova reaches farther.",
		archetype = .Arcanist,
		path = .Arcanist_Nova,
		degree = 1,
		has_prerequisite = false,
		prerequisite = .Warden_Bulwark,
		melee_bonus = 0,
		spell_bonus = 2,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 14,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Frost,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Arcanist_Permafrost = {
		key = "arcanist_permafrost",
		name = "Permafrost Sigils",
		description = "Frost Nova spreads wider and chills longer while Mage Strike chills foes.",
		archetype = .Arcanist,
		path = .Arcanist_Nova,
		degree = 2,
		has_prerequisite = true,
		prerequisite = .Arcanist_Focus,
		melee_bonus = 0,
		spell_bonus = 2,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 8,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Frost,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Arcanist_Overload = {
		key = "arcanist_overload",
		name = "Arc Overload",
		description = "Arc Bolt erupts in a piercing fan.",
		archetype = .Arcanist,
		path = .Arcanist_Bolt,
		degree = 2,
		has_prerequisite = true,
		prerequisite = .Arcanist_Splinter,
		melee_bonus = 0,
		spell_bonus = 3,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 8,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Arcane,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Arcanist_Glacial = {
		key = "arcanist_glacial",
		name = "Glacial Tide",
		description = "Frost Nova reaches farther.",
		archetype = .Arcanist,
		path = .Arcanist_Nova,
		degree = 3,
		has_prerequisite = true,
		prerequisite = .Arcanist_Permafrost,
		melee_bonus = 0,
		spell_bonus = 3,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 10,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Frost,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Arcanist_Pierce = {
		key = "arcanist_pierce",
		name = "Piercing Arc",
		description = "Arc Bolts pierce deeper through enemy ranks.",
		archetype = .Arcanist,
		path = .Arcanist_Bolt,
		degree = 3,
		has_prerequisite = true,
		prerequisite = .Arcanist_Overload,
		melee_bonus = 0,
		spell_bonus = 4,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 8,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Arcane,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Arcanist_Blizzard = {
		key = "arcanist_blizzard",
		name = "Blizzard Heart",
		description = "Frost Nova reaches farther while armor and spellcraft improve.",
		archetype = .Arcanist,
		path = .Arcanist_Nova,
		degree = 4,
		has_prerequisite = true,
		prerequisite = .Arcanist_Glacial,
		melee_bonus = 0,
		spell_bonus = 4,
		armor_bonus = 1,
		max_hp_bonus = 0,
		max_mana_bonus = 14,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Frost,
		cross_path_tag = .Arcane,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 1,
		effect_coverage = .Fully_Wired,
	},
	.Arcanist_Storm = {
		key = "arcanist_storm",
		name = "Conduit Sigil",
		description = "Piercing Arc Bolts retain more force after passing through foes.",
		archetype = .Arcanist,
		path = .Arcanist_Bolt,
		degree = 4,
		has_prerequisite = true,
		prerequisite = .Arcanist_Pierce,
		melee_bonus = 0,
		spell_bonus = 5,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 12,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Arcane,
		cross_path_tag = .Frost,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 1,
		effect_coverage = .Fully_Wired,
	},
	.Arcanist_Absolute_Zero = {
		key = "arcanist_absolute_zero",
		name = "Absolute Zero",
		description = "Frost Nova reaches its widest; master another path and it engulfs the whole room.",
		archetype = .Arcanist,
		path = .Arcanist_Nova,
		degree = 5,
		has_prerequisite = true,
		prerequisite = .Arcanist_Blizzard,
		melee_bonus = 0,
		spell_bonus = 5,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 16,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .None,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Arcanist_Arc_Tyrant = {
		key = "arcanist_arc_tyrant",
		name = "Arc Tyrant",
		description = "Arc Bolts home toward the nearest unhit foe.",
		archetype = .Arcanist,
		path = .Arcanist_Bolt,
		degree = 5,
		has_prerequisite = true,
		prerequisite = .Arcanist_Storm,
		melee_bonus = 0,
		spell_bonus = 6,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 14,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .None,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Arcanist_Charge = {
		key = "arcanist_charge",
		name = "Static Charge",
		description = "Arc Bolt costs less mana.",
		archetype = .Arcanist,
		path = .Arcanist_Storm,
		degree = 1,
		has_prerequisite = false,
		prerequisite = .Warden_Bulwark,
		melee_bonus = 0,
		spell_bonus = 2,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 8,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Storm,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Arcanist_Ward = {
		key = "arcanist_ward",
		name = "Arcane Ward",
		description = "Strengthens armor, expands mana reserves, and steadies their slow return.",
		archetype = .Arcanist,
		path = .Arcanist_Ward,
		degree = 1,
		has_prerequisite = false,
		prerequisite = .Warden_Bulwark,
		melee_bonus = 0,
		spell_bonus = 0,
		armor_bonus = 1,
		max_hp_bonus = 0,
		max_mana_bonus = 12,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Shield,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Arcanist_Chain_Lightning = {
		key = "arcanist_chain_lightning",
		name = "Chain Lightning",
		description = "The cast's shared Storm charge arcs from the earliest Arc Bolt impact to a nearby foe at reduced damage.",
		archetype = .Arcanist,
		path = .Arcanist_Storm,
		degree = 2,
		has_prerequisite = true,
		prerequisite = .Arcanist_Charge,
		melee_bonus = 0,
		spell_bonus = 2,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 8,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Storm,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Arcanist_Ward_Mend = {
		key = "arcanist_ward_mend",
		name = "Warding Mend",
		description = "Strengthens armor, vitality, and mana reserves.",
		archetype = .Arcanist,
		path = .Arcanist_Ward,
		degree = 2,
		has_prerequisite = true,
		prerequisite = .Arcanist_Ward,
		melee_bonus = 0,
		spell_bonus = 0,
		armor_bonus = 2,
		max_hp_bonus = 8,
		max_mana_bonus = 10,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Shield,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Arcanist_Tempest = {
		key = "arcanist_tempest",
		name = "Tempest",
		description = "The Storm chain reaches farther and continues through more foes.",
		archetype = .Arcanist,
		path = .Arcanist_Storm,
		degree = 3,
		has_prerequisite = true,
		prerequisite = .Arcanist_Chain_Lightning,
		melee_bonus = 0,
		spell_bonus = 3,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 10,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Storm,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Arcanist_Ward_Overload = {
		key = "arcanist_ward_overload",
		name = "Ward Overload",
		description = "Strengthens armor, spellcraft, and mana reserves.",
		archetype = .Arcanist,
		path = .Arcanist_Ward,
		degree = 3,
		has_prerequisite = true,
		prerequisite = .Arcanist_Ward_Mend,
		melee_bonus = 0,
		spell_bonus = 2,
		armor_bonus = 2,
		max_hp_bonus = 0,
		max_mana_bonus = 12,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Shield,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Arcanist_Storm_Caller = {
		key = "arcanist_storm_caller",
		name = "Stormcaller",
		description = "The Storm chain reaches farther, strikes more foes, and prioritizes elite, miniboss, and boss prey.",
		archetype = .Arcanist,
		path = .Arcanist_Storm,
		degree = 4,
		has_prerequisite = true,
		prerequisite = .Arcanist_Tempest,
		melee_bonus = 0,
		spell_bonus = 4,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 12,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Storm,
		cross_path_tag = .Frost,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 1,
		effect_coverage = .Fully_Wired,
	},
	.Arcanist_Aegis = {
		key = "arcanist_aegis",
		name = "Arcane Aegis",
		description = "Greatly strengthens armor, vitality, and mana reserves.",
		archetype = .Arcanist,
		path = .Arcanist_Ward,
		degree = 4,
		has_prerequisite = true,
		prerequisite = .Arcanist_Ward_Overload,
		melee_bonus = 0,
		spell_bonus = 0,
		armor_bonus = 3,
		max_hp_bonus = 10,
		max_mana_bonus = 14,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Shield,
		cross_path_tag = .Arcane,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 1,
		effect_coverage = .Stats_Only,
	},
	.Arcanist_World_Storm = {
		key = "arcanist_world_storm",
		name = "World Storm",
		description = "The Storm chain reaches its greatest range and breadth while retaining elite priority.",
		archetype = .Arcanist,
		path = .Arcanist_Storm,
		degree = 5,
		has_prerequisite = true,
		prerequisite = .Arcanist_Storm_Caller,
		melee_bonus = 0,
		spell_bonus = 5,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 14,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .None,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Arcanist_Eternal_Aegis = {
		key = "arcanist_eternal_aegis",
		name = "Eternal Aegis",
		description = "Further strengthens armor, vitality, and mana reserves.",
		archetype = .Arcanist,
		path = .Arcanist_Ward,
		degree = 5,
		has_prerequisite = true,
		prerequisite = .Arcanist_Aegis,
		melee_bonus = 0,
		spell_bonus = 0,
		armor_bonus = 4,
		max_hp_bonus = 14,
		max_mana_bonus = 18,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .None,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Acolyte_Sanguine = {
		key = "acolyte_sanguine",
		name = "Sanguine Rite",
		description = "Blood Rite, Spirit Bolt, and blood-bound familiars siphon health on hit.",
		archetype = .Acolyte,
		path = .Acolyte_Blood,
		degree = 1,
		has_prerequisite = false,
		prerequisite = .Warden_Bulwark,
		melee_bonus = 1,
		spell_bonus = 2,
		armor_bonus = 0,
		max_hp_bonus = 8,
		max_mana_bonus = 0,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Blood,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Acolyte_Veil = {
		key = "acolyte_veil",
		name = "Veil of Ash",
		description = "The mana shield absorbs more damage, Spirit Call costs less mana, and mana seeps back quicker behind the veil.",
		archetype = .Acolyte,
		path = .Acolyte_Veil,
		degree = 1,
		has_prerequisite = false,
		prerequisite = .Warden_Bulwark,
		melee_bonus = 0,
		spell_bonus = 0,
		armor_bonus = 1,
		max_hp_bonus = 0,
		max_mana_bonus = 8,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Veil,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Acolyte_Gravebind = {
		key = "acolyte_gravebind",
		name = "Gravebind Covenant",
		description = "Blood attacks bind foes and siphon more health; killing bound foes while wounded restores health and mana.",
		archetype = .Acolyte,
		path = .Acolyte_Blood,
		degree = 2,
		has_prerequisite = true,
		prerequisite = .Acolyte_Sanguine,
		melee_bonus = 0,
		spell_bonus = 2,
		armor_bonus = 0,
		max_hp_bonus = 6,
		max_mana_bonus = 6,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Blood,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Acolyte_Ashen = {
		key = "acolyte_ashen",
		name = "Ashen Ward",
		description = "Strengthens armor and mana reserves.",
		archetype = .Acolyte,
		path = .Acolyte_Veil,
		degree = 2,
		has_prerequisite = true,
		prerequisite = .Acolyte_Veil,
		melee_bonus = 0,
		spell_bonus = 0,
		armor_bonus = 2,
		max_hp_bonus = 0,
		max_mana_bonus = 10,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Veil,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Acolyte_Blood_Pact = {
		key = "acolyte_blood_pact",
		name = "Blood Pact",
		description = "Health siphon strengthens again, and damaging foes grants additional lifesteal.",
		archetype = .Acolyte,
		path = .Acolyte_Blood,
		degree = 3,
		has_prerequisite = true,
		prerequisite = .Acolyte_Gravebind,
		melee_bonus = 0,
		spell_bonus = 3,
		armor_bonus = 0,
		max_hp_bonus = 10,
		max_mana_bonus = 0,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Blood,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Acolyte_Spirit_Host = {
		key = "acolyte_spirit_host",
		name = "Spirit Host",
		description = "Improves spellcraft and mana reserves.",
		archetype = .Acolyte,
		path = .Acolyte_Veil,
		degree = 3,
		has_prerequisite = true,
		prerequisite = .Acolyte_Ashen,
		melee_bonus = 0,
		spell_bonus = 3,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 10,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Veil,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Acolyte_Crimson_Maw = {
		key = "acolyte_crimson_maw",
		name = "Crimson Maw",
		description = "Blood attacks siphon even more health.",
		archetype = .Acolyte,
		path = .Acolyte_Blood,
		degree = 4,
		has_prerequisite = true,
		prerequisite = .Acolyte_Blood_Pact,
		melee_bonus = 2,
		spell_bonus = 4,
		armor_bonus = 0,
		max_hp_bonus = 14,
		max_mana_bonus = 0,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Blood,
		cross_path_tag = .Veil,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 1,
		effect_coverage = .Fully_Wired,
	},
	.Acolyte_Grave_Chorus = {
		key = "acolyte_grave_chorus",
		name = "Grave Chorus",
		description = "Strengthens armor, spellcraft, and mana reserves.",
		archetype = .Acolyte,
		path = .Acolyte_Veil,
		degree = 4,
		has_prerequisite = true,
		prerequisite = .Acolyte_Spirit_Host,
		melee_bonus = 0,
		spell_bonus = 4,
		armor_bonus = 2,
		max_hp_bonus = 0,
		max_mana_bonus = 14,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Veil,
		cross_path_tag = .Blood,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 1,
		effect_coverage = .Stats_Only,
	},
	.Acolyte_Sanguine_Ascendant = {
		key = "acolyte_sanguine_ascendant",
		name = "Sanguine Ascendant",
		description = "Blood attacks reach their strongest life-siphoning form.",
		archetype = .Acolyte,
		path = .Acolyte_Blood,
		degree = 5,
		has_prerequisite = true,
		prerequisite = .Acolyte_Crimson_Maw,
		melee_bonus = 3,
		spell_bonus = 5,
		armor_bonus = 0,
		max_hp_bonus = 20,
		max_mana_bonus = 0,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Blood,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Acolyte_Undying_Veil = {
		key = "acolyte_undying_veil",
		name = "Undying Veil",
		description = "Further strengthens armor, spellcraft, and mana reserves.",
		archetype = .Acolyte,
		path = .Acolyte_Veil,
		degree = 5,
		has_prerequisite = true,
		prerequisite = .Acolyte_Grave_Chorus,
		melee_bonus = 0,
		spell_bonus = 5,
		armor_bonus = 3,
		max_hp_bonus = 0,
		max_mana_bonus = 16,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Veil,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Acolyte_Spirit_Call = {
		key = "acolyte_spirit_call",
		name = "Spirit Call",
		description = "Spirit Call summons a heartier, stronger crow familiar.",
		archetype = .Acolyte,
		path = .Acolyte_Spirit,
		degree = 1,
		has_prerequisite = false,
		prerequisite = .Warden_Bulwark,
		melee_bonus = 0,
		spell_bonus = 2,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 8,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Spirit,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Acolyte_Curse = {
		key = "acolyte_curse",
		name = "Hex",
		description = "Improves spellcraft and mana reserves, and hexed mana trickles back quicker.",
		archetype = .Acolyte,
		path = .Acolyte_Curse,
		degree = 1,
		has_prerequisite = false,
		prerequisite = .Warden_Bulwark,
		melee_bonus = 0,
		spell_bonus = 2,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 8,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Curse,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Acolyte_Wraith_Host = {
		key = "acolyte_wraith_host",
		name = "Crow Companion",
		description = "The crow familiar grows heartier.",
		archetype = .Acolyte,
		path = .Acolyte_Spirit,
		degree = 2,
		has_prerequisite = true,
		prerequisite = .Acolyte_Spirit_Call,
		melee_bonus = 0,
		spell_bonus = 3,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 8,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Spirit,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Acolyte_Decay = {
		key = "acolyte_decay",
		name = "Decay",
		description = "Further improves spellcraft and mana reserves.",
		archetype = .Acolyte,
		path = .Acolyte_Curse,
		degree = 2,
		has_prerequisite = true,
		prerequisite = .Acolyte_Curse,
		melee_bonus = 0,
		spell_bonus = 3,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 8,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Curse,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Acolyte_Bone_Legion = {
		key = "acolyte_bone_legion",
		name = "Twin Crows",
		description = "Spirit Call expands the crow host and strengthens every familiar's attacks.",
		archetype = .Acolyte,
		path = .Acolyte_Spirit,
		degree = 3,
		has_prerequisite = true,
		prerequisite = .Acolyte_Wraith_Host,
		melee_bonus = 2,
		spell_bonus = 4,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 10,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Spirit,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Acolyte_Fragility = {
		key = "acolyte_fragility",
		name = "Fragility",
		description = "Deepens spellcraft and mana reserves.",
		archetype = .Acolyte,
		path = .Acolyte_Curse,
		degree = 3,
		has_prerequisite = true,
		prerequisite = .Acolyte_Decay,
		melee_bonus = 0,
		spell_bonus = 4,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 10,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Curse,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Acolyte_Wraith_Lord = {
		key = "acolyte_wraith_lord",
		name = "Crow Lord",
		description = "The crow host grows tougher and stronger, and its leader gains a champion's presence.",
		archetype = .Acolyte,
		path = .Acolyte_Spirit,
		degree = 4,
		has_prerequisite = true,
		prerequisite = .Acolyte_Bone_Legion,
		melee_bonus = 3,
		spell_bonus = 5,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 12,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Spirit,
		cross_path_tag = .Curse,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 1,
		effect_coverage = .Fully_Wired,
	},
	.Acolyte_Doom = {
		key = "acolyte_doom",
		name = "Doom",
		description = "Greatly improves spellcraft and mana reserves.",
		archetype = .Acolyte,
		path = .Acolyte_Curse,
		degree = 4,
		has_prerequisite = true,
		prerequisite = .Acolyte_Fragility,
		melee_bonus = 0,
		spell_bonus = 5,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 12,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Curse,
		cross_path_tag = .Spirit,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 1,
		effect_coverage = .Stats_Only,
	},
	.Acolyte_Legion_Eternal = {
		key = "acolyte_legion_eternal",
		name = "Eternal Crows",
		description = "The crow host expands, becomes deathless, and regenerates health.",
		archetype = .Acolyte,
		path = .Acolyte_Spirit,
		degree = 5,
		has_prerequisite = true,
		prerequisite = .Acolyte_Wraith_Lord,
		melee_bonus = 4,
		spell_bonus = 6,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 16,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .None,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Acolyte_Eternal_Doom = {
		key = "acolyte_eternal_doom",
		name = "Eternal Doom",
		description = "Brings spellcraft and mana reserves to their peak.",
		archetype = .Acolyte,
		path = .Acolyte_Curse,
		degree = 5,
		has_prerequisite = true,
		prerequisite = .Acolyte_Doom,
		melee_bonus = 0,
		spell_bonus = 6,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 16,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .None,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Ranger_Snare = {
		key = "ranger_snare",
		name = "Barbed Snares",
		description = "Multishot arrows without a competing poison or chill effect snare foes, and stamina recovers faster.",
		archetype = .Ranger,
		path = .Ranger_Control,
		degree = 1,
		has_prerequisite = false,
		prerequisite = .Warden_Bulwark,
		melee_bonus = 0,
		spell_bonus = 2,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 8,
		speed_bonus = 0.0,
		tag = .Control,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Ranger_Volley = {
		key = "ranger_volley",
		name = "Volley Drills",
		description = "Multishot spreads into a wider fan.",
		archetype = .Ranger,
		path = .Ranger_Volley,
		degree = 1,
		has_prerequisite = false,
		prerequisite = .Warden_Bulwark,
		melee_bonus = 1,
		spell_bonus = 2,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Volley,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Ranger_Beastmark = {
		key = "ranger_beastmark",
		name = "Beastmark Pursuit",
		description = "Hawk Slash snares foes; Vault refunds stamina and hastens Multishot; already-snared foes take more damage.",
		archetype = .Ranger,
		path = .Ranger_Control,
		degree = 2,
		has_prerequisite = true,
		prerequisite = .Ranger_Snare,
		melee_bonus = 1,
		spell_bonus = 0,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 6,
		speed_bonus = 0.12,
		tag = .Control,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Ranger_Rapid = {
		key = "ranger_rapid",
		name = "Rapid Volley",
		description = "Multishot expands into a denser fan.",
		archetype = .Ranger,
		path = .Ranger_Volley,
		degree = 2,
		has_prerequisite = true,
		prerequisite = .Ranger_Volley,
		melee_bonus = 2,
		spell_bonus = 2,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 6,
		speed_bonus = 0.0,
		tag = .Volley,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Ranger_Thornfield = {
		key = "ranger_thornfield",
		name = "Thornfield",
		description = "Improves spellcraft and stamina reserves.",
		archetype = .Ranger,
		path = .Ranger_Control,
		degree = 3,
		has_prerequisite = true,
		prerequisite = .Ranger_Beastmark,
		melee_bonus = 0,
		spell_bonus = 3,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 8,
		speed_bonus = 0.0,
		tag = .Control,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Ranger_Piercing_Volley = {
		key = "ranger_piercing_volley",
		name = "Piercing Volley",
		description = "Multishot arrows pierce through foes.",
		archetype = .Ranger,
		path = .Ranger_Volley,
		degree = 3,
		has_prerequisite = true,
		prerequisite = .Ranger_Rapid,
		melee_bonus = 3,
		spell_bonus = 3,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 0,
		speed_bonus = 0.0,
		tag = .Volley,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Ranger_Hunter_Drive = {
		key = "ranger_hunter_drive",
		name = "Hunter's Drive",
		description = "Improves melee power and stamina reserves, and quickens your stride.",
		archetype = .Ranger,
		path = .Ranger_Control,
		degree = 4,
		has_prerequisite = true,
		prerequisite = .Ranger_Thornfield,
		melee_bonus = 2,
		spell_bonus = 0,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 12,
		speed_bonus = 0.14,
		tag = .Control,
		cross_path_tag = .Beast,
		cross_path_bonus_melee = 1,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Ranger_Storm_Volley = {
		key = "ranger_storm_volley",
		name = "Storm Volley",
		description = "Multishot expands into its widest piercing fan.",
		archetype = .Ranger,
		path = .Ranger_Volley,
		degree = 4,
		has_prerequisite = true,
		prerequisite = .Ranger_Piercing_Volley,
		melee_bonus = 4,
		spell_bonus = 4,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 8,
		speed_bonus = 0.0,
		tag = .Volley,
		cross_path_tag = .Survival,
		cross_path_bonus_melee = 1,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Ranger_Wild_Domination = {
		key = "ranger_wild_domination",
		name = "Wild Domination",
		description = "Improves spellcraft and stamina reserves, and quickens your stride.",
		archetype = .Ranger,
		path = .Ranger_Control,
		degree = 5,
		has_prerequisite = true,
		prerequisite = .Ranger_Hunter_Drive,
		melee_bonus = 0,
		spell_bonus = 5,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 14,
		speed_bonus = 0.1,
		tag = .Control,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Ranger_Sky_Quiver = {
		key = "ranger_sky_quiver",
		name = "Sky Quiver",
		description = "Multishot arrows home toward nearby unhit foes.",
		archetype = .Ranger,
		path = .Ranger_Volley,
		degree = 5,
		has_prerequisite = true,
		prerequisite = .Ranger_Storm_Volley,
		melee_bonus = 5,
		spell_bonus = 5,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 10,
		speed_bonus = 0.0,
		tag = .Volley,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Ranger_Beast_Bond = {
		key = "ranger_beast_bond",
		name = "Beast Bond",
		description = "Spirit Beast gains health and bite damage, while petting restores more health.",
		archetype = .Ranger,
		path = .Ranger_Beast,
		degree = 1,
		has_prerequisite = false,
		prerequisite = .Warden_Bulwark,
		melee_bonus = 2,
		spell_bonus = 0,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 8,
		speed_bonus = 0.0,
		tag = .Beast,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Ranger_Survival = {
		key = "ranger_survival",
		name = "Survivalist",
		description = "Strengthens vitality and stamina reserves.",
		archetype = .Ranger,
		path = .Ranger_Survival,
		degree = 1,
		has_prerequisite = false,
		prerequisite = .Warden_Bulwark,
		melee_bonus = 0,
		spell_bonus = 0,
		armor_bonus = 0,
		max_hp_bonus = 8,
		max_mana_bonus = 0,
		max_stamina_bonus = 10,
		speed_bonus = 0.0,
		tag = .Survival,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Ranger_Pack_Tactics = {
		key = "ranger_pack_tactics",
		name = "Pack Tactics",
		description = "Spirit Beast attacks faster, mauls snared foes harder, and recovers more from petting.",
		archetype = .Ranger,
		path = .Ranger_Beast,
		degree = 2,
		has_prerequisite = true,
		prerequisite = .Ranger_Beast_Bond,
		melee_bonus = 3,
		spell_bonus = 0,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 6,
		speed_bonus = 0.0,
		tag = .Beast,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Ranger_Camouflage = {
		key = "ranger_camouflage",
		name = "Camouflage",
		description = "Expands stamina reserves and quickens your stride.",
		archetype = .Ranger,
		path = .Ranger_Survival,
		degree = 2,
		has_prerequisite = true,
		prerequisite = .Ranger_Survival,
		melee_bonus = 0,
		spell_bonus = 0,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 8,
		speed_bonus = 0.1,
		tag = .Survival,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Ranger_Alpha = {
		key = "ranger_alpha",
		name = "Alpha",
		description = "Spirit Beast grows faster and tougher, knocks foes back, and recovers more from petting.",
		archetype = .Ranger,
		path = .Ranger_Beast,
		degree = 3,
		has_prerequisite = true,
		prerequisite = .Ranger_Pack_Tactics,
		melee_bonus = 4,
		spell_bonus = 0,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 8,
		speed_bonus = 0.0,
		tag = .Beast,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Ranger_Pathfinder = {
		key = "ranger_pathfinder",
		name = "Pathfinder",
		description = "Improves spellcraft and stamina reserves.",
		archetype = .Ranger,
		path = .Ranger_Survival,
		degree = 3,
		has_prerequisite = true,
		prerequisite = .Ranger_Camouflage,
		melee_bonus = 0,
		spell_bonus = 2,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 10,
		speed_bonus = 0.0,
		tag = .Survival,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Ranger_Spirit_Companion = {
		key = "ranger_spirit_companion",
		name = "Spirit Companion",
		description = "Spirit Beast gains arcane bites, health, damage, speed, and stronger recovery from petting.",
		archetype = .Ranger,
		path = .Ranger_Beast,
		degree = 4,
		has_prerequisite = true,
		prerequisite = .Ranger_Alpha,
		melee_bonus = 5,
		spell_bonus = 2,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 10,
		speed_bonus = 0.0,
		tag = .Beast,
		cross_path_tag = .Volley,
		cross_path_bonus_melee = 1,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Ranger_Ambush = {
		key = "ranger_ambush",
		name = "Ambush",
		description = "Improves melee power and stamina reserves, and quickens your stride.",
		archetype = .Ranger,
		path = .Ranger_Survival,
		degree = 4,
		has_prerequisite = true,
		prerequisite = .Ranger_Pathfinder,
		melee_bonus = 4,
		spell_bonus = 0,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 12,
		speed_bonus = 0.12,
		tag = .Survival,
		cross_path_tag = .Control,
		cross_path_bonus_melee = 1,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
	.Ranger_Primal_Lord = {
		key = "ranger_primal_lord",
		name = "Primal Lord",
		description = "Spirit Beast becomes a primal champion, mauls elite and boss prey harder, and recovers greatly from petting.",
		archetype = .Ranger,
		path = .Ranger_Beast,
		degree = 5,
		has_prerequisite = true,
		prerequisite = .Ranger_Spirit_Companion,
		melee_bonus = 6,
		spell_bonus = 3,
		armor_bonus = 0,
		max_hp_bonus = 0,
		max_mana_bonus = 0,
		max_stamina_bonus = 12,
		speed_bonus = 0.0,
		tag = .None,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Fully_Wired,
	},
	.Ranger_Ghost_Step = {
		key = "ranger_ghost_step",
		name = "Ghost Step",
		description = "Strengthens vitality and stamina reserves, and quickens your stride.",
		archetype = .Ranger,
		path = .Ranger_Survival,
		degree = 5,
		has_prerequisite = true,
		prerequisite = .Ranger_Ambush,
		melee_bonus = 0,
		spell_bonus = 0,
		armor_bonus = 0,
		max_hp_bonus = 10,
		max_mana_bonus = 0,
		max_stamina_bonus = 14,
		speed_bonus = 0.16,
		tag = .None,
		cross_path_tag = .None,
		cross_path_bonus_melee = 0,
		cross_path_bonus_spell = 0,
		effect_coverage = .Stats_Only,
	},
}

Discipline_State :: enum u8 {
	Chosen,
	Available,
	Path_Locked,
	Locked,
}

Discipline_Acquire_Result :: enum u8 {
	Acquired,
	Wrong_Archetype,
	Already_Chosen,
	Prerequisite_Locked,
	Path_Locked,
	No_Tokens,
}

Discipline_Combo_Bonus :: struct {
	melee:  int,
	spell:  int,
	max_hp: int,
}

Discipline_Cross_Path_Bonus :: struct {
	melee: int,
	spell: int,
}

discipline_def :: proc(id: Discipline_Id) -> Discipline_Def {
	return DISCIPLINES[id]
}

discipline_by_key :: proc(key: string) -> (Discipline_Id, bool) {
	for id in Discipline_Id {
		if DISCIPLINES[id].key == key do return id, true
	}
	return {}, false
}

discipline_path_at :: proc(archetype: Archetype_Id, column: int) -> (Discipline_Path, bool) {
	if column < 0 || column >= DISCIPLINE_PATHS_PER_ARCHETYPE do return {}, false
	return DISCIPLINE_PATH_LAYOUT[archetype][column], true
}

discipline_at :: proc(path: Discipline_Path, degree: int) -> (Discipline_Id, bool) {
	if degree < 1 || degree > DISCIPLINE_DEGREES do return {}, false
	for id in Discipline_Id {
		def := DISCIPLINES[id]
		if def.path == path && int(def.degree) == degree do return id, true
	}
	return {}, false
}

discipline_path_rank :: proc(player: ^Player, path: Discipline_Path) -> int {
	if player == nil do return 0
	rank := 0
	for id in Discipline_Id {
		if player.acquired_disciplines[id] && DISCIPLINES[id].path == path do rank += 1
	}
	return rank
}

discipline_path_committed :: proc(player: ^Player, path: Discipline_Path) -> bool {
	return discipline_path_rank(player, path) > 0
}

discipline_committed_path_count :: proc(player: ^Player) -> int {
	if player == nil do return 0
	count := 0
	for path in DISCIPLINE_PATH_LAYOUT[player.archetype] {
		if discipline_path_committed(player, path) do count += 1
	}
	return count
}

discipline_path_locked :: proc(player: ^Player, path: Discipline_Path) -> bool {
	if player == nil do return true
	if discipline_path_committed(player, path) do return false
	return discipline_committed_path_count(player) >= MAX_COMMITTED_DISCIPLINE_PATHS
}

discipline_completed_path_count :: proc(player: ^Player) -> int {
	if player == nil do return 0
	count := 0
	for path in DISCIPLINE_PATH_LAYOUT[player.archetype] {
		if discipline_path_rank(player, path) == DISCIPLINE_DEGREES do count += 1
	}
	return count
}

discipline_combo_bonus :: proc(player: ^Player) -> Discipline_Combo_Bonus {
	completed := discipline_completed_path_count(player)
	if completed <= 0 do return {}
	steps := max(0, completed - 1)
	return {
		melee = completed + steps * 2,
		spell = completed + steps * 2,
		max_hp = completed * 6 + steps * 8,
	}
}

discipline_cross_path_bonus :: proc(player: ^Player) -> Discipline_Cross_Path_Bonus {
	result: Discipline_Cross_Path_Bonus
	if player == nil do return result
	for modifier_id in Discipline_Id {
		modifier := DISCIPLINES[modifier_id]
		if !player.acquired_disciplines[modifier_id] || modifier.cross_path_tag == .None do continue
		for target_id in Discipline_Id {
			target := DISCIPLINES[target_id]
			if player.acquired_disciplines[target_id] && target.tag == modifier.cross_path_tag {
				result.melee += modifier.cross_path_bonus_melee
				result.spell += modifier.cross_path_bonus_spell
			}
		}
	}
	return result
}

discipline_state :: proc(player: ^Player, id: Discipline_Id) -> Discipline_State {
	if player == nil do return .Locked
	def := DISCIPLINES[id]
	if player.acquired_disciplines[id] do return .Chosen
	if def.archetype != player.archetype do return .Locked
	if discipline_path_locked(player, def.path) do return .Path_Locked
	if def.has_prerequisite && !player.acquired_disciplines[def.prerequisite] do return .Locked
	return .Available
}

grant_memory_tokens :: proc(player: ^Player, amount := 1) {
	if player == nil || amount <= 0 do return
	player.memory_tokens += amount
}

discipline_try_acquire :: proc(player: ^Player, id: Discipline_Id) -> Discipline_Acquire_Result {
	if player == nil do return .Wrong_Archetype
	def := DISCIPLINES[id]
	if def.archetype != player.archetype do return .Wrong_Archetype
	if player.acquired_disciplines[id] do return .Already_Chosen
	if def.has_prerequisite && !player.acquired_disciplines[def.prerequisite] do return .Prerequisite_Locked
	if discipline_path_locked(player, def.path) do return .Path_Locked
	if player.memory_tokens <= 0 do return .No_Tokens

	// Every rejection above is mutation-free. From here on acquisition cannot
	// fail, so spending the token and applying its bonuses is one atomic action.
	player.memory_tokens -= 1
	player.acquired_disciplines[id] = true
	player.discipline_melee_bonus += def.melee_bonus
	player.discipline_spell_bonus += def.spell_bonus
	player.discipline_armor_bonus += def.armor_bonus
	player.discipline_speed_bonus += def.speed_bonus
	player.max_hp += def.max_hp_bonus
	player.hp = min(player.max_hp, player.hp + def.max_hp_bonus)
	player.max_mana += def.max_mana_bonus
	player.mana = min(f32(player.max_mana), player.mana + f32(def.max_mana_bonus))
	player.max_stamina += def.max_stamina_bonus
	player.stamina = min(f32(player.max_stamina), player.stamina + f32(def.max_stamina_bonus))

	combo := discipline_combo_bonus(player)
	delta_melee := combo.melee - player.discipline_combo_melee_applied
	delta_spell := combo.spell - player.discipline_combo_spell_applied
	delta_hp := combo.max_hp - player.discipline_combo_hp_applied
	player.discipline_melee_bonus += delta_melee
	player.discipline_spell_bonus += delta_spell
	player.max_hp += delta_hp
	player.hp = min(player.max_hp, player.hp + delta_hp)
	player.discipline_combo_melee_applied = combo.melee
	player.discipline_combo_spell_applied = combo.spell
	player.discipline_combo_hp_applied = combo.max_hp

	if def.path == .Rogue_Precision {
		player.precision_rank = u8(discipline_path_rank(player, .Rogue_Precision))
	}
	return .Acquired
}

// Runtime-facing acquisition adds the one canonical live-actor side effect:
// choosing a Beast node immediately refreshes an already-summoned companion.
// Character UI should call this wrapper; tests and save reconstruction can use
// discipline_try_acquire directly when only Player state exists.
run_try_acquire_discipline :: proc(run: ^Run, id: Discipline_Id) -> Discipline_Acquire_Result {
	if run == nil do return .Wrong_Archetype
	result := discipline_try_acquire(&run.player, id)
	if result == .Acquired && DISCIPLINES[id].path == .Ranger_Beast {
		refresh_active_spirit_beast(run, discipline_path_rank(&run.player, .Ranger_Beast), player_has_skill_bonus(&run.player, .Spirit_Beast_Bond))
	}
	return result
}

// Keep the direct rank field as an M8 test/save compatibility seam while live
// progression derives the canonical rank from acquired nodes.
player_precision_rank :: proc(player: ^Player) -> u8 {
	if player == nil do return 0
	return u8(max(int(player.precision_rank), discipline_path_rank(player, .Rogue_Precision)))
}

player_has_discipline :: proc(player: ^Player, id: Discipline_Id) -> bool {
	return player != nil && player.acquired_disciplines[id]
}

// Blood-path siphon ladders (combat/projectiles.py:406-438). Melee strikes
// siphon less than spells; both read live so a mid-run purchase deepens an
// already-summoned host's drain immediately.
acolyte_melee_leech :: proc(player: ^Player) -> int {
	switch {
	case player_has_discipline(player, .Acolyte_Sanguine_Ascendant): return 6
	case player_has_discipline(player, .Acolyte_Crimson_Maw): return 5
	case player_has_discipline(player, .Acolyte_Blood_Pact): return 4
	case player_has_discipline(player, .Acolyte_Gravebind): return 3
	case player_has_discipline(player, .Acolyte_Sanguine): return 2
	case player_has_skill_bonus(player, .Blood_Leech): return 1
	}
	return 0
}

acolyte_spell_leech :: proc(player: ^Player) -> int {
	switch {
	case player_has_discipline(player, .Acolyte_Sanguine_Ascendant): return 8
	case player_has_discipline(player, .Acolyte_Crimson_Maw): return 7
	case player_has_discipline(player, .Acolyte_Blood_Pact): return 5
	case player_has_discipline(player, .Acolyte_Gravebind): return 4
	case player_has_discipline(player, .Acolyte_Sanguine): return 3
	case player_has_skill_bonus(player, .Blood_Leech): return 1
	}
	return 0
}
